apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: givin-secrets-sync
  namespace: givin-system
  labels:
    app.kubernetes.io/name: givin
    app.kubernetes.io/component: secret-management
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: givin-vault-backend
    kind: SecretStore
  target:
    name: givin-secrets
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: givin/production/database
        property: password
    - secretKey: JWT_SECRET
      remoteRef:
        key: givin/production/security
        property: jwt_secret
    - secretKey: MINIO_ROOT_USER
      remoteRef:
        key: givin/production/minio
        property: root_user
    - secretKey: MINIO_ROOT_PASSWORD
      remoteRef:
        key: givin/production/minio
        property: root_password
    - secretKey: HMAC_SIGNING_KEY
      remoteRef:
        key: givin/production/security
        property: hmac_signing_key
