apiVersion: v1
kind: Namespace
metadata:
  name: givin-system
  labels:
    app.kubernetes.io/name: givin
    app.kubernetes.io/part-of: gujarat-integrated-video-intelligence-network
    environment: production
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: givin-compute-quota
  namespace: givin-system
spec:
  hard:
    requests.cpu: "32"
    requests.memory: 64Gi
    limits.cpu: "64"
    limits.memory: 128Gi
    persistentvolumeclaims: "20"
